# Naive Bayes Classification Project

## Stockout Risk Prediction for Retail Inventory

**Company:** Walmart (Retail Industry)

## Problem Faced By Company
Walmart and other similar retail companies  have to manage stock properly. Sometimes products go out of stock when customer demand suddenly increases or supplier delivery gets delayed. This creates a stockout problem, and customers may not get the product on time.

## Solution For The Problem
To solve this problem, we use **Naive Bayes classification model**.  
This model will ppredicts whether whether there is a stockout risk or not.
The model learns from inventory related data like current stock, daily demand, lead time, supplier reliability, and promotion status.

## Purpose of this Project

The purpose of this project is to  predict stockout risk in a retail store using the Naive Bayes algorithm.

## Import Libraries

In [1]:
import pandas as pd                   
import numpy as np

## Load the Dataset
Here we load the dataset and preview the first few rows.

In [2]:
df = pd.read_csv("Dataset/inventory_demand_stockout_risk.csv")
df.head()       # Load the dataset

,product_id,date,store_id,current_stock,daily_demand,lead_time_days,supplier_reliability_score,promotion_active,weather_impact,stockout_risk
0,P1000,2024-01-01,S7,213,114,5,72,No,Medium,No
1,P1001,2024-01-02,S20,152,87,7,84,No,High,Yes
2,P1002,2024-01-03,S15,209,62,10,61,No,Low,No
3,P1003,2024-01-04,S11,400,103,10,61,No,Low,No
4,P1004,2024-01-05,S8,60,114,9,75,No,Medium,No

In [3]:
df.info()  # Information About The Dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  2800 non-null   object
 1   date                        2800 non-null   object
 2   store_id                    2800 non-null   object
 3   current_stock               2800 non-null   int64
 4   daily_demand                2800 non-null   int64
 5   lead_time_days              2800 non-null   int64
 6   supplier_reliability_score  2800 non-null   int64
 7   promotion_active            2800 non-null   object
 8   weather_impact              2800 non-null   object
 9   stockout_risk               2800 non-null   object
dtypes: int64(4), object(6)
memory usage: 218.9+ KB

In [4]:
df.columns # Check the columns name

Index(['product_id', 'date', 'store_id', 'current_stock', 'daily_demand',
       'lead_time_days', 'supplier_reliability_score', 'promotion_active',
       'weather_impact', 'stockout_risk'],
      dtype='object')

In [5]:
df["stockout_risk"].value_counts()  # Count the target count of stockout risk

stockout_risk
No     2110
Yes     690
Name: count, dtype: int64

##  Selecting feature and target
- **X (Feature):** Features that are used for prediction 
- **y (Target):** Stockout Risk

I removed some columns from the features:
- stockout_risk: because it is target column.
- product_id : because it is only a identification column.
- date: because it is not directly used in this model.
- store_id: because it is also an identification column.
- weather_impact: because I am not using this column in this model.

So, the remaining columns are used as input features to predict stockout_risk.

In [6]:
# Select features and target
X = df.drop(["stockout_risk", "product_id", "date", "store_id","weather_impact"], axis = 1)
y = df["stockout_risk"]

In [7]:
X.head() # Features

,current_stock,daily_demand,lead_time_days,supplier_reliability_score,promotion_active
0,213,114,5,72,No
1,152,87,7,84,No
2,209,62,10,61,No
3,400,103,10,61,No
4,60,114,9,75,No

In [8]:
y.head() # Target

0     No
1    Yes
2     No
3     No
4     No
Name: stockout_risk, dtype: object

## Label Encoding

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le = LabelEncoder()
y = le.fit_transform(y)

In this dataset, columns like **promotion_active** and **stockout_risk** contain categorical values, so I converted them into numbers before splitting the data.

In [11]:
X["promotion_active"] = LabelEncoder().fit_transform(X["promotion_active"])
y = le.fit_transform(y)

##  Import Train-Test Split

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
# Split the data into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [14]:
from sklearn.naive_bayes import MultinomialNB

## Train Model Using Naive Bayes
- Here I trained the model using the Multinomial Naive Bayes algorithm.
- Naive Bayes is a classification algorithm that predicts the class based on probability.
- In this project, it predicts the stockout risk category.

In [15]:
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

##  Making Predictions
After training the model, I used the testing data to make predictions.        
The model predicts whether stockout risk is present or not for the test records.

In [16]:
y_pred = model.predict(X_test)
y_pred[:10] # viewing the top 10 predicted values

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [17]:
y_test[:10]  # viewing the top 10 actual values

array([0, 0, 1, 0, 1, 0, 0, 1, 0, 0], dtype=int64)

##  Checking Model Score
Here I checked the accuracy score of the model which tells how many predictions are correct out of total predictions.

In [18]:
model.score(X_test, y_test)

0.7119047619047619

##  Evaluation
We evaluate the model using Classification Report

In [19]:
from sklearn.metrics import classification_report

Classification report shows:

- **Precision:** How many predicted values were actually correct
- **Recall:** How many actual values were correctly found by the model
- **F1-score:** Balance between precision and recall

In [20]:
report = classification_report(y_test, y_pred)
print(report)     # Model Evaluation

              precision    recall  f1-score   support

           0       0.74      0.94      0.83       621
           1       0.26      0.05      0.09       219

    accuracy                           0.71       840
   macro avg       0.50      0.50      0.46       840
weighted avg       0.61      0.71      0.64       840

## Conclusion

- In this project, we used the Naive Bayes classification model to predict stockout risk in retail inventory.
- The model learned from inventory-related features and predicted whether there is a chance of stockout or not which help retail companies like Walmart to manage stock properly and avoid product unavailability.

Overall, this project shows that stockout risk prediction can support better decision-making in retail sales and inventory planning.

# Pipeline Model Using Naive Bayes

Now I am applying the same Naive Bayes model using Pipeline.    
In normal Naive Bayes code, model training and prediction are written separately. But in pipeline we arrange the model in one proper structure.

In [21]:
# Importing Pipeline
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB

In [22]:
pipe = Pipeline([
    ("nb", MultinomialNB())
])
pipe.fit(X_train, y_train)

Pipeline(steps=[('nb', MultinomialNB())])

In [23]:
y_pred_pipe = pipe.predict(X_test)
y_pred_pipe[:10]   # predicting values

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [24]:
y_test[:10] # actual values

array([0, 0, 1, 0, 1, 0, 0, 1, 0, 0], dtype=int64)

##  Checking Model Score
Here I checked the accuracy score of the model which tells how many predictions are correct out of total predictions.

In [25]:
pipe.score(X_test, y_test)

0.7119047619047619

##  Evaluation of pipeline model
We evaluate the model using Classification Report

In [26]:
from sklearn.metrics import classification_report

In [27]:
report = classification_report(y_test, y_pred)
print(report)     # Model Evaluation

              precision    recall  f1-score   support

           0       0.74      0.94      0.83       621
           1       0.26      0.05      0.09       219

    accuracy                           0.71       840
   macro avg       0.50      0.50      0.46       840
weighted avg       0.61      0.71      0.64       840

## Pipeline Result
- Pipeline help us to keep the model training process clean and organized. Mainly instead of writing every step seperately, the pipeline combines the model step by step in one structure
- The main difference is that pipeline makes the code more structured and easy to update in future.